1) create a view of the most popular restaurants by the number of people who have reviewed for them and display their average rating
CREATE VIEW MOST_POPULAR_RESTAURANT (RESTNAME, RID, REVIEWCOUNT, AVGRATING) AS SELECT RESTNAME, REVIEW.RID, COUNT(REVIEW.RID) AS REVIEWCOUNT, AVG(RATINGS) AS AVGRATING FROM RESTAURANTS, REVIEW WHERE RESTAURANTS.RID = REVIEW.RID GROUP BY REVIEW.RID, RESTAURANTS.RESTNAME

2) create a view of the top rated restaurant by the average rating
CREATE VIEW TOP_RATED_REST (RESTNAME, RID, PRICEBRACKET, AVGRATING) AS SELECT RESTNAME, REVIEW.RID, PRICEBRACKET, AVG(RATINGS) AS AVGRATING FROM RESTAURANTS, REVIEW WHERE RESTAURANTS.RID = REVIEW.RID GROUP BY REVIEW.RID, RESTAURANTS.RESTNAME, RESTAURANTS.PRICEBRACKET

1) return the foods served at the most popular restaurant
SELECT FOODNAME, RESTNAME FROM FOODITEM f, MENU m1, MOST_POPULAR_RESTAURANT m where m.RID = m1.RID and m1.MID = f.MID and REVIEWCOUNT = (SELECT max(REVIEWCOUNT) FROM MOST_POPULAR_RESTAURANT)

2) return the names of the people who rated the highest rated retaurant
SELECT FIRSTNAME, LASTNAME, RATINGS, RESTNAME FROM REVIEW R, CUSTOMERS C, TOP_RATED_REST T WHERE C.CID = R.CID AND R.RID = T.RID AND AVGRATING = (SELECT MAX(AVGRATING) FROM TOP_RATED_REST)